#+TITLE: UDS Work list and ideas
#+AUTHOR: Taylor Shin
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* TODO Implement other platforms... namely Fedora, OS X, etc.
** IDEA OS X? huh... I need MONEY! Now all those Apple computers I have are totally outdated and Apple cut down support. So, it will not happen anytime soon!

* TODO Some automatic update checking system? Many open source projects implement rss feed to notify newer versions.
** DONE At least version checking has been implemented.
** IDEA Do we need any sub-project?

* TODO Some web-based system using rails. (far fetched)
** TODO We might need to implement or sketch up a GUI version of the script first.
** IDEA Actually, we can implement some kind of Web(HTML2) based management interface with ruby.

* PROJ Emacs native-compiler
** DONE It works on Kubuntu (Ubuntu).
** DONE emacs-nc works perfectly well on RHEL!!
** KILL Fedora, Manjaro has their own repo (or additional repo) to install emacs-nc. So, don't bother with them.
*** NO Apparently, they actually work well with source compilation. Even AUR is a source compile install. So, why would I care about them?
** Holy cow, RHEL is failing to compile gccemacs again! signal.h inclusion probme... huh.

* Looks like the changed made on openSUSE doesn't affect negatively on other distribution. Debian was successfully built emacs-nc!! Probably, Ubuntu won't have similar issue either.
