#+TITLE: UDS Work list and ideas
#+AUTHOR: Taylor Shin
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* TODO Implement other platforms... namely Fedora, OS X, etc.
** IDEA OS X? huh... I need MONEY! Now all those Apple computers I have are totally outdated and Apple cut down support. So, it will not happen anytime soon!

* TODO Some automatic update checking system? Many open source projects implement rss feed to notify newer versions.
** DONE At least version checking has been implemented.
** IDEA Do we need any sub-project?

* TODO Some web-based system using rails. (far fetched)
** TODO We might need to implement or sketch up a GUI version of the script first.
** IDEA Actually, we can implement some kind of Web(HTML2) based management interface with ruby.

* IDEA RamFS? or tmpFS?
** Apparently, we do not need to keep all the build directories at all! Once the are installed and packaged, build directories are just waste of space.
** We have 'clean' functionality, though. But the speed advantage from Ram drive is not to be trifled with!! It's DAMN fast! We can reduce build time significantly.
** Of course, we need at least 10 GB of idle RAM space to use the Ramfs reliably. Other than that, big stuffs like GCC won't be able to be compiled simply within any Ramfs.

